"""AgyAdapter — ~/.gemini/antigravity-cli/ projects, sessions, and artifacts.

Real on-disk format for Antigravity CLI (agy):
  - Base dir: ~/.gemini/antigravity-cli/ (overridable via AGY_HOME or ANTIGRAVITY_HOME)
  - Sessions:
      * brain/<conversation_id>/.system_generated/logs/transcript.jsonl
        Each line is a JSON record representing a step:
          - USER_INPUT (or source USER_EXPLICIT): user request
          - PLANNER_RESPONSE: model thinking, response text, tool_calls
          - Tool results: GENERIC, VIEW_FILE, RUN_COMMAND, CODE_ACTION,
            LIST_DIRECTORY, GREP_SEARCH, SEARCH_WEB, READ_URL_CONTENT, etc.
          - SYSTEM_MESSAGE: runtime notifications/system messages
      * brain/<conversation_id>/*.md: artifacts generated by the agent during session
        (walkthrough.md, task.md, implementation_plan.md, reports)
      * history.jsonl: lines of {conversationId, workspace, display, timestamp}
      * conversation_summaries.db: SQLite DB with conversation_id, title, preview,
        step_count, last_modified_time, workspace_uris
      * settings.json: CLI settings including model and trustedWorkspaces
      * conversations/<conversation_id>.(db|pb): trajectory databases
"""
from __future__ import annotations

import json
import os
import re
import shutil
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

from . import AgentAdapter, Capabilities
from .common import (
    SessionSummary, context_limit_for, iter_jsonl, read_doc_file,
    read_git_info, save_doc_file,
)


def agy_home() -> Path:
    for var in ("AGY_HOME", "ANTIGRAVITY_HOME", "ANTIGRAVITY_CLI_HOME"):
        env = os.environ.get(var)
        if env:
            return Path(env).expanduser()
    default = Path.home() / ".gemini" / "antigravity-cli"
    if not default.exists() and (Path.home() / ".antigravity").exists():
        return Path.home() / ".antigravity"
    return default


def _mangle(cwd: str) -> str:
    return cwd.replace("/", "-").replace("\\", "-").replace(":", "-")


def _unmangle_path(name: str) -> str:
    if "--" in name:
        name = name.replace("--", ":/", 1)
    return name.replace("-", "/")


def _clean_user_prompt(text: str) -> str:
    if not text:
        return ""
    m = re.search(r"<USER_REQUEST>\s*(.*?)\s*</USER_REQUEST>", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    cleaned = re.sub(r"<ADDITIONAL_METADATA>.*?</ADDITIONAL_METADATA>", "", text, flags=re.DOTALL)
    cleaned = re.sub(r"<USER_SETTINGS_CHANGE>.*?</USER_SETTINGS_CHANGE>", "", cleaned, flags=re.DOTALL)
    return cleaned.strip() or text.strip()


def _clean_args(args: Any) -> Any:
    if isinstance(args, dict):
        cleaned = {}
        for k, v in args.items():
            if isinstance(v, str):
                v_str = v.strip()
                if (v_str.startswith('"') and v_str.endswith('"')) or (
                    v_str.startswith("'") and v_str.endswith("'")
                ):
                    try:
                        v = json.loads(v_str)
                    except Exception:
                        v = v_str[1:-1]
            cleaned[k] = v
        return cleaned
    return args


def _extract_ws_from_transcript(path: Path) -> str:
    """Peek the head of transcript to deduce working directory if metadata missing."""
    if not path.is_file():
        return ""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            for i, line in enumerate(f):
                if i > 25:
                    break
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                except json.JSONDecodeError:
                    continue
                content = d.get("content") or ""
                if isinstance(content, str):
                    m = re.search(r"Your working directory is\s+([^\s\n]+)", content)
                    if m:
                        p = m.group(1).rstrip("/")
                        if "/.agents" in p:
                            p = p.split("/.agents")[0]
                        return p
                    m2 = re.search(r"Project working directory:\s+([^\s\n]+)", content)
                    if m2:
                        p = m2.group(1).rstrip("/")
                        if "/.agents" in p:
                            p = p.split("/.agents")[0]
                        return p
                for tc in d.get("tool_calls", []) or []:
                    args = tc.get("args") or {}
                    for k in ("Cwd", "DirectoryPath", "SearchDirectory"):
                        if k in args and isinstance(args[k], str):
                            v = args[k].strip('"').strip("'")
                            if v.startswith("/"):
                                if "/.agents" in v:
                                    v = v.split("/.agents")[0]
                                return v
    except OSError:
        pass
    return ""


def _scan_sessions(home: Path) -> tuple[dict[str, list[dict[str, Any]]], dict[str, dict[str, Any]]]:
    """Scan all AGY sessions and group them by project cwd.
    
    Returns:
      (projects_map, sessions_by_id)
    """
    brain = home / "brain"
    if not brain.is_dir():
        return {}, {}

    # 1. Read history.jsonl
    history_map: dict[str, str] = {}
    h_file = home / "history.jsonl"
    if h_file.is_file():
        for rec in iter_jsonl(h_file):
            cid = rec.get("conversationId")
            ws = rec.get("workspace")
            if cid and ws and cid not in history_map:
                history_map[cid] = ws

    # 2. Read conversation_summaries.db
    db_map: dict[str, str] = {}
    parent_map: dict[str, str] = {}
    titles_map: dict[str, str] = {}
    preview_map: dict[str, str] = {}
    db_file = home / "conversation_summaries.db"
    if db_file.is_file():
        try:
            conn = sqlite3.connect(db_file)
            cursor = conn.execute(
                "SELECT conversation_id, title, preview, workspace_uris, parent_conversation_id "
                "FROM conversation_summaries"
            )
            for cid, title, preview, w_uris, pid in cursor.fetchall():
                if title:
                    titles_map[cid] = title
                if preview:
                    preview_map[cid] = preview
                if pid:
                    parent_map[cid] = pid
                try:
                    uris = json.loads(w_uris) if w_uris else []
                    if uris and isinstance(uris, list):
                        p = uris[0]
                        if p.startswith("file://"):
                            p = p[7:]
                        db_map[cid] = p
                except Exception:
                    pass
            conn.close()
        except Exception:
            pass

    # 3. Read default model from settings.json
    default_model = "Gemini 3.8 Flash"
    settings_file = home / "settings.json"
    if settings_file.is_file():
        try:
            st = json.loads(settings_file.read_text(encoding="utf-8"))
            if st.get("model"):
                default_model = st["model"]
        except Exception:
            pass

    projects_map: dict[str, list[dict[str, Any]]] = {}
    sessions_by_id: dict[str, dict[str, Any]] = {}

    for d in brain.iterdir():
        if not d.is_dir():
            continue
        cid = d.name
        tfile = d / ".system_generated" / "logs" / "transcript.jsonl"
        if not tfile.is_file():
            continue

        # Resolve workspace
        ws = db_map.get(cid) or history_map.get(cid)
        if not ws and parent_map.get(cid):
            parent = parent_map[cid]
            ws = db_map.get(parent) or history_map.get(parent)
        if not ws:
            ws = _extract_ws_from_transcript(tfile)
        if not ws:
            ws = str(Path.home())

        st = tfile.stat()
        info = {
            "session_id": cid,
            "cwd": ws,
            "transcript_path": tfile,
            "mtime": st.st_mtime,
            "size_bytes": st.st_size,
            "title": titles_map.get(cid, ""),
            "preview": preview_map.get(cid, ""),
            "default_model": default_model,
        }
        sessions_by_id[cid] = info
        projects_map.setdefault(ws, []).append(info)

    return projects_map, sessions_by_id


class AgyAdapter(AgentAdapter):
    capabilities = Capabilities(
        agent_id="agy",
        label="Antigravity (agy)",
        doc_filename="GEMINI.md",
        has_memory=True,
        has_tasks=False,
        can_edit_doc=True,
        can_delete=True,
        can_export=True,
    )

    def _home(self) -> Path:
        return agy_home()

    def _project_cwd(self, project: str) -> str:
        """Resolve mangled or direct project identifier to working directory."""
        projects, _ = _scan_sessions(self._home())
        for cwd in projects:
            if _mangle(cwd) == project or cwd == project:
                return cwd
        # Fallback to unmangle approximation
        return _unmangle_path(project)

    def list_projects(self) -> list[dict[str, Any]]:
        home = self._home()
        projects, _ = _scan_sessions(home)
        out: list[dict[str, Any]] = []

        for cwd, sessions in projects.items():
            if not sessions:
                continue
            mtimes = [s["mtime"] for s in sessions]
            name = _mangle(cwd)
            # Check if memory/artifacts exist
            brain = home / "brain"
            has_mem = False
            for s in sessions:
                sid = s["session_id"]
                s_brain = brain / sid
                if s_brain.is_dir():
                    for f in s_brain.glob("*.md"):
                        if not f.name.endswith(".metadata.json"):
                            has_mem = True
                            break
                if has_mem:
                    break
            if not has_mem and cwd:
                has_mem = (Path(cwd) / ".agents").is_dir() or (Path(cwd) / "memory").is_dir()

            has_doc = False
            if cwd:
                has_doc = (Path(cwd) / "GEMINI.md").is_file() or (Path(cwd) / "AGENTS.md").is_file()

            out.append({
                "name": name,
                "display_path": cwd,
                "cwd": cwd,
                "session_count": len(sessions),
                "has_memory": has_mem,
                "has_claude_md": has_doc,
                "open_tasks": 0,
                "total_tasks": 0,
                "git": read_git_info(cwd),
                "mtime": max(mtimes),
            })

        out.sort(key=lambda p: p["mtime"], reverse=True)
        return out

    def list_sessions(self, project: str) -> list[SessionSummary]:
        home = self._home()
        projects, _ = _scan_sessions(home)
        cwd = self._project_cwd(project)
        sessions = projects.get(cwd, [])
        if not sessions:
            # Fallback search by matching mangled name
            for w, s_list in projects.items():
                if _mangle(w) == project:
                    cwd = w
                    sessions = s_list
                    break

        git = read_git_info(cwd)
        branch = git["branch"] if git else ""
        out: list[SessionSummary] = []

        for s_info in sessions:
            cid = s_info["session_id"]
            tfile: Path = s_info["transcript_path"]
            if not tfile.is_file():
                continue

            first_prompt = ""
            last_prompt = s_info.get("preview", "")
            user_turns = 0
            asst_turns = 0
            total_turns = 0
            model = s_info.get("default_model", "")
            total_chars = 0
            asst_chars = 0

            for rec in iter_jsonl(tfile):
                stype = rec.get("type")
                src = rec.get("source")
                content = rec.get("content") or ""
                thinking = rec.get("thinking") or ""
                if isinstance(content, str):
                    total_chars += len(content)
                if isinstance(thinking, str):
                    total_chars += len(thinking)

                if stype == "USER_INPUT" or src == "USER_EXPLICIT":
                    user_turns += 1
                    total_turns += 1
                    clean = _clean_user_prompt(content if isinstance(content, str) else "")
                    if clean:
                        if not first_prompt:
                            first_prompt = clean[:500]
                        last_prompt = clean[:500]
                elif stype == "PLANNER_RESPONSE":
                    asst_turns += 1
                    total_turns += 1
                    if isinstance(content, str):
                        asst_chars += len(content)
                elif stype in (
                    "GENERIC", "VIEW_FILE", "RUN_COMMAND", "CODE_ACTION",
                    "LIST_DIRECTORY", "GREP_SEARCH", "SEARCH_WEB",
                    "READ_URL_CONTENT", "ASK_QUESTION",
                ):
                    total_turns += 1

            est_context = total_chars // 4
            est_output = asst_chars // 4
            win = context_limit_for(est_context)

            # Check if this session has artifacts
            s_brain = home / "brain" / cid
            has_mem = False
            if s_brain.is_dir():
                for f in s_brain.glob("*.md"):
                    if not f.name.endswith(".metadata.json"):
                        has_mem = True
                        break

            summ = SessionSummary(
                session_id=cid,
                project=project,
                file=str(tfile),
                size_bytes=s_info["size_bytes"],
                mtime=s_info["mtime"],
                first_prompt=first_prompt,
                last_prompt=last_prompt,
                message_count=total_turns,
                user_turns=user_turns,
                assistant_turns=asst_turns,
                context_tokens=est_context,
                context_limit=win["limit"],
                context_limit_known=win["known"],
                total_output_tokens=est_output,
                model=model,
                git_branch=branch,
                cwd=cwd,
                has_memory=has_mem,
                agent="agy",
                title=s_info.get("title", ""),
            )
            out.append(summ)

        out.sort(key=lambda s: s.mtime, reverse=True)
        return out

    def get_conversation(self, project: str, session_id: str,
                         offset: int = 0, limit: int | None = None) -> dict[str, Any]:
        tfile = self._home() / "brain" / session_id / ".system_generated" / "logs" / "transcript.jsonl"
        if not tfile.is_file():
            return {"total": 0, "offset": offset, "limit": limit, "turns": []}

        turns: list[dict[str, Any]] = []
        for rec in iter_jsonl(tfile):
            stype = rec.get("type")
            src = rec.get("source")
            idx = rec.get("step_index", 0)
            ts = rec.get("created_at", "")
            content = rec.get("content") or ""
            thinking = rec.get("thinking") or ""

            if stype == "USER_INPUT" or src == "USER_EXPLICIT":
                clean_text = _clean_user_prompt(content if isinstance(content, str) else "")
                turns.append({
                    "uuid": str(idx),
                    "role": "user",
                    "kind": "user",
                    "timestamp": ts,
                    "model": "",
                    "blocks": [{"type": "text", "text": clean_text}],
                    "attribution_skill": None,
                    "attribution_plugin": None,
                    "output_tokens": 0,
                })
            elif stype == "PLANNER_RESPONSE":
                blocks = []
                if thinking and isinstance(thinking, str) and thinking.strip():
                    blocks.append({"type": "thinking", "text": thinking})
                if content and isinstance(content, str) and content.strip():
                    blocks.append({"type": "text", "text": content})
                for tc in rec.get("tool_calls", []) or []:
                    if isinstance(tc, dict):
                        blocks.append({
                            "type": "tool_use",
                            "name": tc.get("name", "?"),
                            "input": _clean_args(tc.get("args", {})),
                        })
                if blocks:
                    out_tok = len(content) // 4 if isinstance(content, str) else 0
                    turns.append({
                        "uuid": str(idx),
                        "role": "assistant",
                        "kind": "assistant",
                        "timestamp": ts,
                        "model": "",
                        "blocks": blocks,
                        "attribution_skill": None,
                        "attribution_plugin": None,
                        "output_tokens": out_tok,
                    })
            elif stype in (
                "GENERIC", "VIEW_FILE", "RUN_COMMAND", "CODE_ACTION",
                "LIST_DIRECTORY", "GREP_SEARCH", "SEARCH_WEB",
                "READ_URL_CONTENT", "ASK_QUESTION",
            ):
                txt = content if isinstance(content, str) else json.dumps(content, ensure_ascii=False)
                turns.append({
                    "uuid": str(idx),
                    "role": "user",
                    "kind": "tool",
                    "timestamp": ts,
                    "model": "",
                    "blocks": [{"type": "tool_result", "text": txt}],
                    "attribution_skill": None,
                    "attribution_plugin": None,
                    "output_tokens": 0,
                })
            elif stype == "SYSTEM_MESSAGE":
                if isinstance(content, str) and content.strip():
                    turns.append({
                        "uuid": str(idx),
                        "role": "user",
                        "kind": "tool",
                        "timestamp": ts,
                        "model": "",
                        "blocks": [{"type": "text", "text": content}],
                        "attribution_skill": None,
                        "attribution_plugin": None,
                        "output_tokens": 0,
                    })

        total = len(turns)
        end = total if limit is None else min(total, offset + limit)
        return {
            "total": total,
            "offset": offset,
            "limit": limit,
            "turns": turns[offset:end],
        }

    def iter_turns(self, project: str, session_id: str) -> Iterator[dict[str, Any]]:
        conv = self.get_conversation(project, session_id, offset=0, limit=None)
        for seq, turn in enumerate(conv["turns"]):
            yield {
                "seq": seq,
                "role": turn["role"],
                "kind": turn["kind"],
                "timestamp": turn.get("timestamp", ""),
                "blocks": turn["blocks"],
            }

    def get_doc(self, project: str) -> dict[str, Any]:
        cwd = self._project_cwd(project)
        if not cwd:
            return {"exists": False, "path": "", "content": "", "cwd": ""}
        for fname in ("GEMINI.md", "AGENTS.md"):
            p = Path(cwd) / fname
            if p.is_file():
                return read_doc_file(cwd, fname)
        return read_doc_file(cwd, "GEMINI.md")

    def save_doc(self, project: str, content: str) -> Path:
        cwd = self._project_cwd(project)
        if not cwd:
            raise FileNotFoundError("no working directory known for this project")
        # If AGENTS.md exists and GEMINI.md doesn't, write to AGENTS.md
        if (Path(cwd) / "AGENTS.md").is_file() and not (Path(cwd) / "GEMINI.md").is_file():
            return save_doc_file(cwd, "AGENTS.md", content)
        return save_doc_file(cwd, "GEMINI.md", content)

    def get_memory(self, project: str) -> dict[str, Any]:
        cwd = self._project_cwd(project)
        home = self._home()
        projects, _ = _scan_sessions(home)
        sessions = projects.get(cwd, [])
        if not sessions:
            for w, s_list in projects.items():
                if _mangle(w) == project:
                    cwd = w
                    sessions = s_list
                    break

        files: list[dict[str, Any]] = []
        seen_paths: set[str] = set()

        # 1. Collect session artifacts from brain/<cid>/*.md
        brain = home / "brain"
        for s in sessions:
            cid = s["session_id"]
            s_brain = brain / cid
            if s_brain.is_dir():
                for f in sorted(s_brain.glob("*.md")):
                    if f.name.endswith(".metadata.json"):
                        continue
                    p_str = str(f)
                    if p_str in seen_paths:
                        continue
                    seen_paths.add(p_str)
                    files.append({
                        "name": f"{cid[:8]}_{f.name}",
                        "path": p_str,
                        "content": f.read_text(encoding="utf-8", errors="replace"),
                    })

        # 2. Collect rules or memory files from <cwd>/.agents/ or <cwd>/memory/
        if cwd:
            for base_dir in (Path(cwd) / ".agents" / "rules", Path(cwd) / ".agents", Path(cwd) / "memory"):
                if base_dir.is_dir():
                    for f in sorted(base_dir.glob("*.md")):
                        p_str = str(f)
                        if p_str in seen_paths:
                            continue
                        seen_paths.add(p_str)
                        files.append({
                            "name": f.name,
                            "path": p_str,
                            "content": f.read_text(encoding="utf-8", errors="replace"),
                        })

        index_lines = ["# Antigravity Project Artifacts & Memory", ""]
        if files:
            index_lines.append(f"Found {len(files)} artifact(s) and document(s):")
            index_lines.append("")
            for f in files:
                index_lines.append(f"- **{f['name']}** (`{f['path']}`)")
        else:
            index_lines.append("_No artifacts or memory files found for this project._")

        index_content = "\n".join(index_lines)
        return {
            "index": index_content,
            "index_path": str(Path(cwd) / ".agents") if cwd else "",
            "dir": cwd,
            "files": files,
        }

    def save_memory_file(self, project: str, name: str, content: str) -> Path:
        if "/" in name or "\\" in name or name in ("", ".", ".."):
            raise ValueError("invalid memory file name")
        if not name.endswith(".md"):
            raise ValueError("memory files must end in .md")
        cwd = self._project_cwd(project)
        if not cwd:
            raise FileNotFoundError("no working directory known for this project")
        target_dir = Path(cwd) / ".agents" / "rules"
        target_dir.mkdir(parents=True, exist_ok=True)
        out = target_dir / name
        out.write_text(content, encoding="utf-8")
        return out

    def export_session_markdown(self, project: str, session_id: str) -> str:
        data = self.get_conversation(project, session_id, offset=0, limit=None)
        cwd = self._project_cwd(project)
        lines = [f"# Session {session_id}", f"_Project: {project}_", f"_Working Directory: {cwd}_", ""]
        for t in data["turns"]:
            role = t["kind"]
            ts = t.get("timestamp") or ""
            header = f"## {role}"
            if ts:
                header += f"  ·  {ts}"
            lines.append(header)
            for b in t["blocks"]:
                bt = b["type"]
                if bt == "text":
                    lines.append(b["text"])
                elif bt == "thinking":
                    lines.append(f"> _(thinking)_\n>\n> " + b["text"].replace("\n", "\n> "))
                elif bt == "tool_use":
                    inp = json.dumps(b["input"], indent=2, ensure_ascii=False)
                    lines.append(f"**→ tool: {b['name']}**\n\n```json\n{inp}\n```")
                elif bt == "tool_result":
                    txt = b.get("text", "")
                    lines.append(f"**tool result**\n\n```\n{txt}\n```")
                lines.append("")
            lines.append("")
        return "\n".join(lines)

    def export_session_to_file(self, project: str, session_id: str, out_dir: Path | None = None) -> Path:
        if out_dir is None:
            out_dir = Path.cwd() / "exports" / project
        out_dir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        out_path = out_dir / f"{session_id}.{stamp}.md"
        out_path.write_text(self.export_session_markdown(project, session_id), encoding="utf-8")
        return out_path

    def save_session_as_memory(self, project: str, session_id: str) -> Path:
        """Distill an AGY session into a summary markdown file in project memory."""
        cwd = self._project_cwd(project)
        if not cwd:
            raise FileNotFoundError("no working directory known for this project")
        summ = None
        for s in self.list_sessions(project):
            if s.session_id == session_id:
                summ = s
                break
        if summ is None:
            raise FileNotFoundError(f"session {session_id} not found in {project}")

        short = session_id[:8]
        body = [
            "---",
            f"name: session-{short}",
            f"description: archived summary of Antigravity session {short} in {project}",
            "metadata:",
            "  type: reference",
            "---",
            "",
            f"Archived summary of Antigravity session `{session_id}` (project `{project}`), saved before deletion via cc_mgr.",
            "",
            f"- **Turns:** {summ.message_count} ({summ.user_turns} user / {summ.assistant_turns} assistant)",
            f"- **Context size:** ~{summ.context_tokens} tokens",
            f"- **Model:** {summ.model or 'n/a'}    **Git branch:** {summ.git_branch or 'n/a'}",
            "",
            f"**First prompt:** {summ.first_prompt or '(none)'}",
            "",
            f"**Last prompt:** {summ.last_prompt or '(none)'}",
            "",
        ]

        target_dir = Path(cwd) / ".agents" / "rules"
        target_dir.mkdir(parents=True, exist_ok=True)
        out = target_dir / f"session_{short}.md"
        out.write_text("\n".join(body), encoding="utf-8")
        return out

    def delete_session(self, project: str, session_id: str, hard: bool = False) -> dict[str, Any]:
        """Delete an AGY session (soft delete by default to .cc_mgr_trash)."""
        home = self._home()
        brain_dir = home / "brain" / session_id
        conv_dir = home / "conversations"
        conv_files = list(conv_dir.glob(f"{session_id}.*")) if conv_dir.is_dir() else []

        moved: list[str] = []
        if hard:
            if brain_dir.is_dir():
                shutil.rmtree(brain_dir)
                moved.append(str(brain_dir))
            for cf in conv_files:
                if cf.is_file():
                    cf.unlink()
                    moved.append(str(cf))
            # Delete row from conversation_summaries.db
            db_file = home / "conversation_summaries.db"
            if db_file.is_file():
                try:
                    conn = sqlite3.connect(db_file)
                    conn.execute("DELETE FROM conversation_summaries WHERE conversation_id=?", (session_id,))
                    conn.commit()
                    conn.close()
                except Exception:
                    pass
            return {"deleted": moved, "trash": None}

        # Soft delete: move artifacts to trash directory
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        trash = home / ".cc_mgr_trash" / f"{session_id}.{stamp}"
        trash.mkdir(parents=True, exist_ok=True)

        if brain_dir.is_dir():
            dest = trash / "brain"
            shutil.move(str(brain_dir), str(dest))
            moved.append(str(brain_dir))
        for cf in conv_files:
            if cf.is_file():
                dest = trash / cf.name
                shutil.move(str(cf), str(dest))
                moved.append(str(cf))

        # Also remove row from active conversation_summaries.db
        db_file = home / "conversation_summaries.db"
        if db_file.is_file():
            try:
                conn = sqlite3.connect(db_file)
                conn.execute("DELETE FROM conversation_summaries WHERE conversation_id=?", (session_id,))
                conn.commit()
                conn.close()
            except Exception:
                pass

        return {"deleted": moved, "trash": str(trash)}
